  
name: Release Package
on: [release]
jobs:
  release-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          version: 12.x

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1

      - name: Publish
        run: yarn publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}