  
name: ReleasePage
on: [push]
jobs:
  release-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          version: 12.x

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1

      - name: Install example deps (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: example

      - name: Build
        run: cd example && yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/dist
          cname: react-push-preview.notifo.io